# 使用 Python 官方基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 将当前文件夹内容复制到容器中
COPY . .

# 安装依赖
RUN pip install Flask prometheus_client

# 暴露端口
EXPOSE 8081

# 启动应用
CMD ["python", "demo_webservice.py"]
