apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-prometheus-app-monitor
  namespace: default
  labels:
    #  ServiceMonitor 中指定这个标签是为了确保该资源被 Prometheus Operator 识别并管理，使 Prometheus 能够自动抓取与 ServiceMonitor 关联的服务指标。
    # 这个label要匹配CRD类型是Prometheus的，名字是prometheus-kube-prometheus-prometheus的这里：".spec.probeSelector.matchLabels.release: prometheus"
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-prometheus-app
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 5s
