apiVersion: v1
kind: Service
metadata:
  name: python-prometheus-service
  labels:
    app: python-prometheus-app
spec:
  selector:
    app: python-prometheus-app
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP