alertmanager:
  config:
    receivers:
    - name: "null"
    - name: "slack-receiver"
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: slack-webhook-secret
            key: webhook
          channel: '#kubernate'
          text: 'my test'
    route:
      group_by:
      - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
      - matchers:
        - alertname = "Watchdog"
        receiver: "null"
      - matchers:
        - alertname = "HighCPUUsage"
        receiver: "slack-receiver"
      