apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  webhook: 'https://hooks.slack.com/services/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'
