apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-argocd-app
  namespace: argocd-app
  labels:
    app: python-argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-argocd-app
  template:
    metadata:
      labels:
        app: python-argocd-app
    spec:
      containers:
        - name: python-argocd-app
          image: argocd_demo_webservice:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 10
            periodSeconds: 10
