apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  selector:
    app: springboot-app
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
